version: '3.9' # version ของ docker compose
services:
  # Database คือ mysql container ครับ เพื่อที่จะทำเป็น database
  database:
    container_name: mysql
    # ส่วนนี้เราจะดึง image มาตรง ๆ เลยครับโดยที่เราไม่สร้าง Dockerfile 
    # เพราะเราไม่ต้องการจะ เซตคำสั่งอะไรเพิ่มเติมแล้ว
    image: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql # ครับเช่นเคย volume database เข้ามาในเครื่องเราที่จะเก็บข้อมูลใน database ไว้
      - ./mysql/log:/var/log/mysql # ครับเช่นเคย volume database เข้ามาในเครื่องเราที่จะเก็บข้อมูลใน database ไว้
      - ./mysql/conf.d:/etc/mysql/conf.d # ครับเช่นเคย volume database เข้ามาในเครื่องเราที่จะเก็บข้อมูลใน database ไว้
    environment:
      # สำหรับคนที่ต้องการดู config เพิ่มเติม https://hub.docker.com/_/mysql/
      - MYSQL_DATABASE=laravel # ชื่อ database ซึ่งที่จะสร้างขึ้นหลังจาก container ถูกสร้างแล้ว
      - MYSQL_USER=user # username ของ database ที่เราสร้างไว้
      - MYSQL_PASSWORD=password # password ของ database ที่เราสร้างไว้
      - MYSQL_ROOT_PASSWORD=root # password สำหรับ root database หากต้องการ
      - TZ="Asia/Bangkok"
    ports:
        - 3306:3306 # port ที่เราต้องการจะใช้ระหว่าง {host}:{container} นะครับ

  # Phpmyadmin (optional) อันนี้เพิ่มเติม หากว่าเราต้องการที่จะ explore database อันนี้ขี้เกียจอธิบายละ 5555
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
        - 8890:80
    environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=database
        - PMA_PORT=3306
        - PMA_USER=root
        - PMA_PASSWORD=root
    restart: always
    depends_on:
        - database